server:
  port: 7000
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: 12345678
    key-alias: tomcat
    key-password: 12345678

spring:
  application:
    name: SPRING-GATEWAY
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: route-service
          uri: lb://ROUTE-SERVICE
          order: 3
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
        - id: accommodation-service
          uri: lb://ACCOMMODATION-SERVICE
          order: 2
          predicates:
            - Path=/api/v1/accommodations/**
          filters:
            - StripPrefix=3
        - id: ticket-service
          uri: lb://TICKET-SERVICE
          order: 1
          predicates:
            - Path=/api/v1/tickets/**
          filters:
            - StripPrefix=3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka