server:
  port: 0

yandex-gpt:
  uri: "https://llm.api.cloud.yandex.net/foundationModels/v1/completion"
  iam-token: "t1.9euelZqZk42alsbMnorPy5COzMuajO3rnpWazYyMx5bPmZqdjseXyZ6XyZDl8_dYeFdN-e8qN0FJ_t3z9xgnVU357yo3QUn-zef1656Vmo2Lm8rIjpyKlprOipSMicyY7_zN5_XrnpWaxo7HnZbPmJXOl5ybyZGblcvv_cXrnpWajYubysiOnIqWms6KlIyJzJg.dxFxRB1V5RQORK4fhlsmomY6gB9BNFVcb5a2U9H2QjZbllyQL8DdXNOrL1Swv7063tv1-f2G0sPGbQyHOwNdAg"
  model-uri: "gpt://b1g3bmolh8ou09grrbt8/yandexgpt/latest"
  stream: false
  temperature: 0.3
  maxTokens: 3000

jwt:
  access-time: 600000
  refresh-time: 600000000
  secret-key: ${SECRET_KEY:aPdSgVkYp3s6v9y$B&E)H+MbQeThWmZq4t7w!z%C*F-JaNcRfUjXn2r5u8x/A?D(G+KbPeSgVkYp3s6v9y$B&E)H@McQfTjWmZq4t7w!z%C*F-JaNdRgUkXp2r5u8x/A?D(G+KbPeShVmYq3t6v9y$B&E)H@McQfTjWnZr4u7x!z%C*F-JaNdRgUkXp2s5v8y/B?D(G+KbPeShVmYq3t6w9z$C&F)H@McQfTjWnZr4u7x!A%D*G-KaNdRgUkXp2s5v8y/B?E(H+MbQeShVmYq3t6w9z$C&F)J@NcRfUjWnZr4u7x!A%D*G-KaPdSgVkYp2s5v8y/B?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRfUjXn2r5u8x!A%D*G-KaPdSgVkYp3s6v9y$B?E(H+MbQeThWmZq4t7w!z%C*F)J@NcRfUjXn2r5u8x/A?D(G+KaPdSgVkYp3s6v9y$B&E)H@McQeThWmZq4t7w!z%C*F-JaNdRgUkXn2r5u8x/A?D(G+}

spring:
  application:
    name: ROUTE-SERVICE
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka