server:
  port: 0

yandex-gpt:
  uri: "https://llm.api.cloud.yandex.net/foundationModels/v1/completion"
  iam-token: "t1.9euelZqcnZeYjo6Pz4_HycyNypWbmu3rnpWazYyMx5bPmZqdjseXyZ6XyZDl8_c6FVVN-e9WJ0d3_N3z93pDUk3571YnR3f8zef1656Vms6JkMaKkMzKnImQks3Nm8uM7_zN5_XrnpWaxo7HnZbPmJXOl5ybyZGblcvv_cXrnpWazomQxoqQzMqciZCSzc2by4w.SCQos0D5ulliaEgBhOu087BwFobN6G6QVMvQ1PBQCux6es8UNACwlWrqNCOtffq-XRkHNTaMIaamlKjYePnzDQ"
  model-uri: "gpt://b1g3bmolh8ou09grrbt8/yandexgpt/latest"
  stream: false
  temperature: 0.3
  maxTokens: 3000

jwt:
  access-time: 600000
  refresh-time: 600000000
  secret-key: ${SECRET_KEY:aPdSgVkYp3s6v9y$B&E)H+MbQeThWmZq4t7w!z%C*F-JaNcRfUjXn2r5u8x/A?D(G+KbPeSgVkYp3s6v9y$B&E)H@McQfTjWmZq4t7w!z%C*F-JaNdRgUkXp2r5u8x/A?D(G+KbPeShVmYq3t6v9y$B&E)H@McQfTjWnZr4u7x!z%C*F-JaNdRgUkXp2s5v8y/B?D(G+KbPeShVmYq3t6w9z$C&F)H@McQfTjWnZr4u7x!A%D*G-KaNdRgUkXp2s5v8y/B?E(H+MbQeShVmYq3t6w9z$C&F)J@NcRfUjWnZr4u7x!A%D*G-KaPdSgVkYp2s5v8y/B?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRfUjXn2r5u8x!A%D*G-KaPdSgVkYp3s6v9y$B?E(H+MbQeThWmZq4t7w!z%C*F)J@NcRfUjXn2r5u8x/A?D(G+KaPdSgVkYp3s6v9y$B&E)H@McQeThWmZq4t7w!z%C*F-JaNdRgUkXn2r5u8x/A?D(G+}

spring:
  application:
    name: ROUTE-SERVICE
  data:
    redis:
      database: 16
      host: localhost
      port: 6379
      password: redis-password
      timeout: 60000

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:thesisdb}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka